os: linux
dist: xenial
language: node_js
node_js:
  - "stable"
notifications:
  email: true
cache:
  directories:
    - node_modules
script:
  - yarn build
deploy:
  strategy: git
  provider: pages
  cleanup: true
  token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build
  on:
    branch: master
