language: node_js
node_js:
  - "stable"
notifications:
  email: true
cache:
  directories:
    - node_modules
script:
  - yarn test --watchAll=false
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build
  on:
    branch: master
